"""create tables

Revision ID: 88bc6e27af6f
Revises: 
Create Date: 2026-06-02 20:44:39.043821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88bc6e27af6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name_author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('city',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name_city', sa.String(), nullable=False),
    sa.Column('days_delivery', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('name_genre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('step',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('name_step', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_book_amount_non_negative'),
    sa.CheckConstraint('price > 0', name='ck_book_price_positive'),
    sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_book_author_id'), 'book', ['author_id'], unique=False)
    op.create_index(op.f('ix_book_genre_id'), 'book', ['genre_id'], unique=False)
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name_client', sa.String(length=100), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_client_city_id'), 'client', ['city_id'], unique=False)
    op.create_table('buy',
    sa.Column('buy_id', sa.Integer(), nullable=False),
    sa.Column('buy_description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('buy_id')
    )
    op.create_index(op.f('ix_buy_client_id'), 'buy', ['client_id'], unique=False)
    op.create_table('buy_book',
    sa.Column('buy_book_id', sa.Integer(), nullable=False),
    sa.Column('buy_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_buy_book_amount_positive'),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buy_id'], ['buy.buy_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('buy_book_id'),
    sa.UniqueConstraint('buy_id', 'book_id', name='uq_buy_book_buy_id_book_id')
    )
    op.create_index(op.f('ix_buy_book_book_id'), 'buy_book', ['book_id'], unique=False)
    op.create_index(op.f('ix_buy_book_buy_id'), 'buy_book', ['buy_id'], unique=False)
    op.create_table('buy_step',
    sa.Column('buy_step_id', sa.Integer(), nullable=False),
    sa.Column('buy_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('date_buy_beg', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_step_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buy_id'], ['buy.buy_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['step.step_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('buy_step_id')
    )
    op.create_index(op.f('ix_buy_step_buy_id'), 'buy_step', ['buy_id'], unique=False)
    op.create_index(op.f('ix_buy_step_step_id'), 'buy_step', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buy_step_step_id'), table_name='buy_step')
    op.drop_index(op.f('ix_buy_step_buy_id'), table_name='buy_step')
    op.drop_table('buy_step')
    op.drop_index(op.f('ix_buy_book_buy_id'), table_name='buy_book')
    op.drop_index(op.f('ix_buy_book_book_id'), table_name='buy_book')
    op.drop_table('buy_book')
    op.drop_index(op.f('ix_buy_client_id'), table_name='buy')
    op.drop_table('buy')
    op.drop_index(op.f('ix_client_city_id'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_book_genre_id'), table_name='book')
    op.drop_index(op.f('ix_book_author_id'), table_name='book')
    op.drop_table('book')
    op.drop_table('step')
    op.drop_table('genre')
    op.drop_table('city')
    op.drop_table('author')
    # ### end Alembic commands ###
